### ISSUE TITLE
[COOK-4032] - 7-zip cookbook name causes LWRP compile error

### ISSUE THREAD

**Issue by someara** [sneal/7-zip#3]
I'm adding an 'archive' LWRP to the 7-zip cookbook. Consuming this resource would like this:
7zip_archive extract_dir do
source archive_path
end
Unfortunately this will produce a compile error:
[2013-11-21T22:58:17-08:00] DEBUG: backtrace entry for compile error: 'C:/opscode/chef/embedded/lib/ruby/gems/1.9.1/gems/chef-11.4.0/lib/chef/provider/lwrp_base.rb:89:in `const_defined?''
[2013-11-21T22:58:17-08:00] DEBUG: Line number of compile error: '89'
Recipe Compile Error in ../cookbooks/7-zip/providers/archive.rb
NameError
---------
wrong constant name 7ZipArchive
7 is a not a valid leading character in a Ruby constant or variable name. This is a problem for the 7-zip cookbook since LWRPs are prefixed by the cookbook name and eventually turned into a constant somewhere. It seems like we'd need to rename the cookbook from '7-zip' to 'seven-zip' to allow LWRPs to be added to this cookbook.

**Comment by sneal** [comment]
Fixed my moving to seven_zip cookbook
