### ISSUE TITLE
[COOK-3879] - 7-zip LWRP to extract archives (ISOs)

### ISSUE THREAD

**Issue by someara** [sneal/7-zip#4]
It would very handy to have a 7-zip LWRP to be able to extract archives.
Specifically I want to extract ISOs on Windows; there is no native way to do this on Windows (at least pre-Win8) from the command line. 7-zip supports extracting ISOs.
Since most MS software is available as ISOs I find myself writing a lot of execute resources in my cookbooks to shell out to 7-zip to first extract an ISO before calling the windows_package resource.
On the other hand it would be even better if the windows_package resource supported ISOs, but I'm not sure that's really a good idea since ISOs aren't an installer.

**Comment by nhudacin** [comment]
This is an old issue so I'm not sure if the functionality was added and the issue was never updated. I think this cookbook does handle extracting ISO's as an LWRP: 

```ruby
# extract the iso image (only if 'source' is an iso)
seven_zip_archive 'extract_sqlserver_iso' do
  path extract_location
  source node['sqlserver']['source']
  overwrite true
  not_if { installation_media_type != '.iso' || instance_already_installed }
end
```

**Comment by sneal** [comment]
Fixed my moving to seven_zip cookbook which does have an archive LWRP
