### ISSUE TITLE
Relationship to seven_zip?

### ISSUE THREAD

**Issue by webframp** [sneal/7-zip#7]
It's a little unclear which 7zip cookbook is the official community cookbook. Seems like @sneal is a contributor to both, so I'm asking here.

Which one is considered _current_ this cookbook or https://github.com/daptiv/seven_zip ?

I noticed that the visual studio cookbook uses seven_zip so my initial inclination is to use that one.

**Comment by sneal** [comment]
The seven_zip cookbook replaces the 7-zip cookbook. The name had to be changed to support creating an LWRP because Ruby doesn't allow you to have a class that starts with a number, i.e. 7.

**Comment by webframp** [comment]
That's what it seemed like. Thanks for clarifying!
